# -*- coding: utf-8 -*-
"""Abid

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRvoobiGuGPJDwHB7LzROcpY08MbJ30b
"""

import pandas as pd

dataframe = pd.DataFrame({"Nama": ["Abid Sabyano Rozhan"], "NIM": ["1103220222"]})