# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5EH-3gQFFGCazz5G1mX3IZer8hd7Bke
"""

def identitas():
  print("Nama: Kevin Radinka")
  print("Nim: 1103223152")
  print("Kelas: TK4602")
  print("Matakuliah: Pemrograman Lanjut")

identitas()