# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5EH-3gQFFGCazz5G1mX3IZer8hd7Bke
"""

import pandas as pd

dataframe = pd.DataFrame({"Nama": ["Kenneth Matthew Yonathan"], "NIM": ["1103220070"]})

import pandas as pd

dataframe = pd.DataFrame({"Nama": ["Kevin Radinka"], "NIM": ["1103223152"]})